# Generated by Django 5.2.4 on 2025-07-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Puzzle, Ação, Estratégia', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('arquivo_jogo', models.FileField(upload_to='arquivos_jogos/')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='potplayapp.categoria')),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
