# Generated by Django 5.2 on 2025-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potplayapp', '0003_jogo_status_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
