# Generated by Django 5.2.4 on 2025-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potplayapp', '0004_jogo_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
